library(ggplot2)
library(plyr)
library(data.table)
library(grid)
setwd("/Users/pesto/Documents/school/Coursera/eda")
HPC <- read.table("household_power_consumption.txt",sep=";",skip=23437,nrows=50000,header=FALSE)
hpcdf<-rbind(HPC[HPC$V1=="1/2/2007",],HPC[HPC$V1=="2/2/2007",])
names(hpcdf)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
hpcdf$Global_active_power<-factor(hpcdf$Global_active_power)
hpcdf.fac<-factor(hpcdf$Global_active_power)
hpcdf$gap<-as.numeric(as.character(hpcdf.fac))
png('plot1.png')
plot1hist<-hist(hpcdf$gap,col="red",breaks=12,ylim=c(0,1200),xlab="Global Active Power (killowats)", main="Global Active Power")
dev.off()