library(ggplot2)
library(plyr)
library(data.table)
library(grid)
library(scales)
library(reshape)
setwd("/Users/pesto/Documents/school/Coursera/eda")
HPC <- read.table("household_power_consumption.txt",sep=";",skip=23437,nrows=50000,header=FALSE)
hpcdf<-rbind(HPC[HPC$V1=="1/2/2007",],HPC[HPC$V1=="2/2/2007",])
names(hpcdf)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
hpcdf$Date<-as.Date(hpcdf$Date,"%d/%m/%Y")
hpcdf$dtime<-strptime(paste(hpcdf$Date,hpcdf$Time), "%Y-%m-%d %H:%M:%S")
hpcdf$ctime<-as.character(hpcdf$dtime)
hpcdf$Sub_metering_1<-as.numeric(as.character(hpcdf$Sub_metering_1))
hpcdf$Sub_metering_2<-as.numeric(as.character(hpcdf$Sub_metering_2))
tomelt<-cbind(hpcdf$ctime,hpcdf$Sub_metering_1,hpcdf$Sub_metering_2,hpcdf$Sub_metering_3)
tmdf<-as.data.frame(tomelt)
names(tmdf)<-c("time","Sub_metering_1","Sub_metering_2","Sub_metering_3")
toplot<-melt(tmdf,id.vars="time")
toplot$time<-strptime(toplot$time, "%Y-%m-%d %H:%M:%S")
toplot$value<-as.numeric(as.character(toplot$value))
png('plot3.png')
dfplot<-ggplot(toplot, aes(x=time, y=value, group=variable, colour=variable )) + geom_line()
dfplot1 <- dfplot + scale_y_discrete(breaks=c("0","10","20","30")) + ylab("Energy sub metering")
dfplot2 <- dfplot1 + scale_x_datetime(breaks="1 day",labels=date_format("%a")) + xlab("")
dfplot3 <- dfplot2 + theme(legend.position=c(.90,.98)) + scale_colour_manual(values=c("black","red","blue"))
dfplot3 +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                  panel.background = element_blank(), axis.line = element_line(color = "black"),
                  legend.background=element_rect(color="black"),axis.text.x = element_text(color="black"),
                  axis.text.y = element_text(color="black"))
dev.off()
